INSERT INTO countries (id, name)
VALUES (1, 'Egypt'),
       (2, 'Saudi Arabia'),
       (3, 'United Arab Emirates'),
       (4, 'Kuwait'),
       (5, 'Qatar'),
       (6, 'Bahrain'),
       (7, 'Oman'),
       (8, 'Jordan'),
       (9, 'Lebanon'),
       (10, 'Syria'),
       (11, 'Iraq'),
       (12, 'Libya'),
       (13, 'Tunisia'),
       (14, 'Algeria'),
       (15, 'Morocco'),
       (16, 'Sudan'),
       (17, 'Yemen'),
       (18, 'Palestine'),
       (19, 'United States'),
       (20, 'United Kingdom'),
       (21, 'Germany'),
       (22, 'France'),
       (23, 'Canada'),
       (24, 'Australia'),
       (25, 'Turkey'),
       (26, 'Italy'),
       (27, 'Netherlands'),
       (28, 'Romania'),
       (29, 'Ireland'),
       (30, 'Spain'),
       (31, 'Portugal'),
       (32, 'Belgium'),
       (33, 'Sweden'),
       (34, 'Norway'),
       (35, 'Denmark'),
       (36, 'Finland'),
       (37, 'Switzerland'),
       (38, 'Austria'),
       (39, 'Poland'),
       (40, 'Czech Republic'),
       (41, 'Hungary'),
       (42, 'Greece'),
       (43, 'Ukraine');