INSERT INTO majors (name)
VALUES ('Computer Science'),
       ('Business Information Systems'),
       ('Software Engineering'),
       ('Information Technology'),
       ('Artificial Intelligence'),
       ('Data Science'),
       ('Cybersecurity'),
       ('Computer Engineering'),
       ('Electrical Engineering'),
       ('Mechanical Engineering'),
       ('Civil Engineering'),
       ('Business Administration'),
       ('Accounting'),
       ('Finance'),
       ('Marketing'),
       ('Economics'),
       ('Architecture'),
       ('Medicine'),
       ('Pharmacy'),
       ('Law');